front:
  build: .
  ports:
    - "80:80"
  links:
    - mysql:mysql
  volumes:
    - ./src:/var/www

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=forum
